@startuml                          

' CLASSES

class Pessoa {

    ' Atributos
    ' ---------
    -String nome
    -int idade

    ' Métodos
    ' --------
    +String getNome()
    +void setNome()
    +int getIdade()
    +void setIdade()
    +void falar()
}

@enduml